### ISSUE TITLE
NullReferenceException from MultipleObjectsTransfer when using UploadDirectoryAsync (possible hang on upload completion)

### ISSUE THREAD

**Issue by AaronZendt** [Azure/azure-storage-net-data-movement#29] opened 2016-04-21 14:55 UTC
Using 0.2.0 of DMLib to facilitate transferring a set of files from a local physical disk to Azure Blob storage (on Azure Gov) via UploadDirectoryAsync.  Testing with 12 files totaling roughly ~500 MB.

I'd guess about 50% of the time, we catch this exception on our app's unobserved handler:

`TaskScheduler.UnobservedTaskException:` Task`1. Message:
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
Exception: 1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.WindowsAzure.Storage.DataMovement.MultipleObjectsTransfer.<DoTransfer>d__16.MoveNext()`

We've put the upload method in it's own method in our app:

`private static Task UploadToDirectory(TransferLocation source, TransferContext context, CancellationToken cToken, CloudBlobDirectory destination)
        {
            var uploadOptions = new UploadDirectoryOptions
            {
                BlobType = BlobType.BlockBlob,
                Recursive = true,
                SearchPattern = "*"
            };
            return XferManager.UploadDirectoryAsync(source.SourceUri.LocalPath, destination, uploadOptions, context, cToken);
        }`

Nothing exotic there.  Just aliasing TransferManager as XferManager as we have an existing type named that.

I pulled the UploadDirectoryAsync logic out of our production application into a test application to isolate it from our code. I wired up all the transfer context events to see all the file behaviour, as well as the operation context to monitor the requests.  All files transfer without skips or fails, but the method's task never completes. I don't see any lingering requests. I think our production application is more aggressive in terminating the task, as I was able to leave the test app running overnight without the method ever completing.  Just hangs and never completes.

Tried swapping the 6.2 Azure Storage library for 7.0 (and 7.0.1-preview) without any difference.  Not sure if this an Azure Gov vs Commercial issue, a bug in the Data Movement library, or some interaction between the two.

**Comment by nowenL** [comment] 2016-06-20 03:02
Thanks for reporting this issue. It's a bug in DataMovement library. This bug is caused by a race condition during object disposing, it can be triggered after all files are transferred in directory transfer.  This bug would be fixed in our next release.

**Comment by hasonmsft** [comment] 2016-10-20 08:03
@AaronZendt , this issue has been fixed and could you try the latest version 0.3? 

Thanks,
Haibo

**Closed** 2017-02-14 03:44 UTC
