### ISSUE TITLE
"Failed to validate destination." when using UploadDirectoryAsync

### ISSUE THREAD

**Issue by PraveenArunagiri** [Azure/azure-storage-net-data-movement#240] opened 2020-10-27 12:31 UTC
### Which service(blob, file) does this issue concern? 
Blob
 
### Which version of the SDK was used?
11.1.3

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)
.Net

### How can the problem be reproduced? It'd be better if the code caused the problem can be shared.
            string path = ROOT_DIRECTORY + "\\" + pathSuffix;
            CloudFileDirectory directory = rootDirectory.GetDirectoryReference(path);
            UploadDirectoryOptions options = new UploadDirectoryOptions()
            {
                Recursive = true,
                PreserveSMBAttributes = true
            };

            DirectoryTransferContext context = new DirectoryTransferContext()
            {
                ProgressHandler = new Progress<TransferStatus>((progress) =>
                {
                    setFileTransferProgress(progress);
                })
            };
            await TransferManager.UploadDirectoryAsync(src, directory, options, context);
 
### What problem was encountered?
I'm getting this exception randomly without any pattern.

System.AggregateException: One or more errors occurred. ---> Microsoft.Azure.Storage.DataMovement.TransferException: Failed to validate destination. ---> System.AggregateException: One or more errors occurred. ---> Microsoft.Azure.Storage.StorageException: A task was canceled. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Storage.Core.Executor.Executor.<ExecuteAsync>d__1`1.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Storage.Core.Executor.Executor.<ExecuteAsync>d__1`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Storage.DataMovement.AzureBlobDirectoryLocation.Validate()
   at Microsoft.Azure.Storage.DataMovement.DirectoryTransfer.<ExecuteAsync>d__30.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Storage.DataMovement.DirectoryTransfer.<ExecuteAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Storage.DataMovement.TransferManager.<DoTransfer>d__92.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Storage.DataMovement.TransferManager.<UploadDirectoryInternalAsync>d__89.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AzureStorage.AzStorageHandler.<moveDataFromWindowsToBlob>d__1c.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at AzureStorage.AzStorageHandler.moveDataFromWindows(String src, String pathSuffix)
 
### Have you found a mitigation/solution?
No

**Comment by blueww** [comment] 2020-10-28 02:53
@PraveenArunagiri 

Thanks for reporting this issue!

From the exception, the failure normally cause the server request to handle File directory timeout, this can caused by some temperate network issue. 
In this case, you can resume from the checkpoint in the transfercontext, with same commandline, see sample in https://github.com/Azure/azure-storage-net-data-movement/blob/4580f93498c64605b65c814e4a3fef1c7acc3e91/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L182

We might can find more detail for this failure from server log (anyway, if the request timeout before reach server, we can't see server log). If you can share the account name, share name, directory name and repo time (UTC), we can try to find server log for it.

**Comment by PraveenArunagiri** [comment] 2020-11-06 10:42
I can't disclose the account and share name coz it happened in our client's environment. Other than checkpoint resume will retry after a sleep work? 
DMlib version - 1.3.0

**Comment by blueww** [comment] 2020-11-09 02:57
@PraveenArunagiri 

Thanks for the reply!

Have you tried resume for this error? Does it work for your scenario?
Besides that, as the DMlib version is 1.3.0, would you like to upgrade to DMlib 2.0.0, it will be more stable than 1.3.0.

And as you can't share the storage account name, we can't see it from server log.

**Comment by blueww** [comment] 2020-11-18 09:35
@PraveenArunagiri

As not hear from your for more than 1 week, I will close this issue.
Feel free to contact us again if you need any further support on DMlib.

**Closed by blueww** 2020-11-18 09:35 UTC
