### ISSUE TITLE
Azure Emulator and DownloadAsync

### ISSUE THREAD

**Issue by premiaware** [Azure/azure-storage-net-data-movement#160] opened 2019-01-10 15:37 UTC
Using UWP Net Standard 2

Using DownloadAsync method with Azure Emulator for download the Blob that not exist

the DownloadAsync method not exit and freeze the thread

Task task1 = TransferManager.DownloadAsync(sourceBlob1, destinationStream, options, sharedTransferContext);

**Comment by blueww** [comment] 2019-01-11 02:38
@premiaware 

How long the thread will be freeze? Is it longer than 15 mins? 
For the not exist blob, does that Account exist, can other exist blobs in the same account be downloaded?

In the freeze time longer than 15 mins, could you get a dump for the issue and share with us, then we can do the investigte.

**Comment by premiaware** [comment] 2019-01-11 09:31
freeze more than 15 mins. I have stopped debugger after about 20min.

With the same account other blobs working well.
How can set the timeout for download blob?

My UWP App don't can waiting more time because the blob image download process increase resources usage and the App crash.

How can share the dump information? I use Visual studio 2018, save as dump create 600Mb of file.

**Comment by blueww** [comment] 2019-01-14 08:42
We can't set the timeout, and DMlib use 15 mins timeout for not reachable blob.

You might can upload the dump as a blob, and send a SAS link for the blob, which has read access, to my mail weiwei@microsoft.com. (Please don't put the blob link here, for here is public.)

**Comment by blueww** [comment] 2019-01-17 07:33
We still don't know the root cause of the issue. 
But you can try to add you own code to check the blob exist, and only transfer when it exist. Let us know if the issue still repro or not.

**Comment by premiaware** [comment] 2019-01-17 07:51
In your Lib don't have a method for check blob exist?

**Comment by blueww** [comment] 2019-01-17 08:06
Since I am not sure where the freeze happen, if check too later might can't block the freeze.
So I would suggest add your own code to check the blob exist. The code should not be complex, just one API.

**Comment by blueww** [comment] 2019-01-22 10:59
@premiaware 
Let me know if you still need help from us?
I will close the issue after several days if not hear from you.

**Closed** 2019-04-25 12:48 UTC
