### ISSUE TITLE
Failed to import Azure table

### ISSUE THREAD

**Issue by DeV1L** [Azure/azure-storage-net-data-movement#129] opened 2018-05-29 12:11 UTC
I have an Azure Tables and their backups in the Blob Storage. 

[![enter image description here][1]][1] [![enter image description here][2]][2]

When I trying to restore it using AzCopy some are restored but some are got an error.

**Success**

    [2018/05/29 12:01:49.463+03:00][VERBOSE] 6.1.0 : AzCopy /Source:https://arenaxtablesbackup.blob.core.windows.net/arenaxstorage/2018-05-28 /Dest:https://arenaxstoragedev.table.core.windows.net/LeaderboardDaily /SourceKey:****** /Destkey:****** /Manifest:arenaxstorage_LeaderboardDaily.manifest /EntityOperation:InsertOrReplace /Z /V
    [2018/05/29 12:01:52.531+03:00][VERBOSE] Uploaded entities: 0    Downloaded blobs: 1, transferred bytes: 191 B
    [2018/05/29 12:01:52.758+03:00] Validating the integrity of data file list...
    [2018/05/29 12:01:52.974+03:00] Validation of data file list passed.
    [2018/05/29 12:01:53.208+03:00] 
    Transfer summary:
    -----------------
    Total entities transferred: 0
    Elapsed time:               00.00:00:03
    [2018/05/29 12:04:57.932+03:00] >>>>>>>>>>>>>>>>
    [2018/05/29 12:04:57.937+03:00][VERBOSE] 6.1.0 : AzCopy /Source:https://arenaxtablesbackup.blob.core.windows.net/arenaxstorage/2018-05-28 /Dest:https://arenaxstoragedev.table.core.windows.net/LeaderboardUser /SourceKey:****** /Destkey:****** /Manifest:arenaxstorage_LeaderboardUser.manifest /EntityOperation:InsertOrReplace /Z /V
    [2018/05/29 12:05:01.189+03:00][VERBOSE] Uploaded entities: 0    Downloaded blobs: 1, transferred bytes: 209 B
    [2018/05/29 12:05:01.440+03:00] Validating the integrity of data file list...
    [2018/05/29 12:05:01.679+03:00] Validation of data file list passed.
    [2018/05/29 12:05:01.903+03:00][VERBOSE] Uploaded entities: 0    Downloaded blobs: 1 of 2, transferred bytes: 209 B
    [2018/05/29 12:05:01.903+03:00][VERBOSE] Uploaded entities: 0    Downloaded blobs: 1 of 2, transferred bytes: 209 B
    [2018/05/29 12:05:01.904+03:00][VERBOSE] Uploaded entities: 0    Downloaded blobs: 1 of 2, transferred bytes: 209 B
    [2018/05/29 12:05:01.904+03:00][VERBOSE] Uploaded entities: 0    Downloaded blobs: 1 of 2, transferred bytes: 209 B
    [2018/05/29 12:05:04.149+03:00][VERBOSE] Uploaded entities: 0    Downloaded blobs: 1 of 2, transferred bytes: 4 MB
    [2018/05/29 12:05:23.741+03:00][VERBOSE] Uploaded entities: 0    Downloaded blobs: 1 of 2, transferred bytes: 8 MB
    [2018/05/29 12:05:23.747+03:00][VERBOSE] Uploaded entities: 0    Downloaded blobs: 1 of 2, transferred bytes: 9.53 MB
    [2018/05/29 12:05:23.753+03:00][VERBOSE] Uploaded entities: 0    Downloaded blobs: 1 of 2, transferred bytes: 9.53 MB
    [2018/05/29 12:05:23.753+03:00][VERBOSE] Uploaded entities: 0    Downloaded blobs: 1 of 2, transferred bytes: 9.53 MB
    [2018/05/29 12:05:23.756+03:00][VERBOSE] Uploaded entities: 0
    [2018/05/29 12:05:23.823+03:00] Validating the integrity of data file "arenaxstorage_LeaderboardUser_0_0_C0DC932F526179D7.json"...
    [2018/05/29 12:05:23.849+03:00] Validation of data file "arenaxstorage_LeaderboardUser_0_0_C0DC932F526179D7.json" passed.
    [2018/05/29 12:05:26.463+03:00][VERBOSE] Uploaded entities: 100
    [2018/05/29 12:05:27.667+03:00][VERBOSE] Uploaded entities: 500
    ...
    [2018/05/29 12:08:18.882+03:00][VERBOSE] Uploaded entities: 21600
    [2018/05/29 12:08:19.024+03:00][VERBOSE] Uploaded entities: 21704
    [2018/05/29 12:08:19.040+03:00] 
    Transfer summary:
    -----------------
    Total entities transferred: 21704
    Elapsed time:               00.00:03:21

**Error**

    [2018/05/29 12:10:44.537+03:00] >>>>>>>>>>>>>>>>
    [2018/05/29 12:10:44.543+03:00][VERBOSE] 6.1.0 : AzCopy /Source:https://arenaxtablesbackup.blob.core.windows.net/arenaxstorage/2018-05-28 /Dest:https://arenaxstoragedev.table.core.windows.net/Leaderboard /SourceKey:****** /Destkey:****** /Manifest:arenaxstorage_Leaderboard.manifest /EntityOperation:InsertOrReplace /Z /V
    [2018/05/29 12:10:47.659+03:00][VERBOSE] Uploaded entities: 0    Downloaded blobs: 1, transferred bytes: 205 B
    [2018/05/29 12:10:47.895+03:00] Validating the integrity of data file list...
    [2018/05/29 12:10:48.276+03:00][ERROR] Failed to import Azure table. Detailed error: Data validation failed. Data files are missing or have been renamed.

What is the problem?

  [1]: https://i.stack.imgur.com/aCU0O.png
  [2]: https://i.stack.imgur.com/JGYHQ.png

**Comment by DeV1L** [comment] 2018-05-30 09:30
When I exported this table to CSV and tried to import by Storage Explorer, I got the error:
![image](https://user-images.githubusercontent.com/8911626/40711759-b41b5d44-6404-11e8-94d6-e73c36689f01.png)
Original table has additional columns starting this line:
![image](https://user-images.githubusercontent.com/8911626/40711922-0ae5ae54-6405-11e8-91c0-3178be50aff9.png)

**Comment by DeV1L** [comment] 2018-05-31 08:47
I found that import fails at the line starting from which a new columns was added to the table.
And it's possible to import the table using Table Service REST API.

**Comment by blueww** [comment] 2018-06-04 07:04
@DeV1L 

From the error, it seems the exported data files count doesn't match the file count record in the manifest file.

As I see, you use customized manifest file name "arenaxstorage_LeaderboardUser.manifest". So would you please check: in the same fold of manifest file

- the count of data *.json file, name pattern is "arenaxstorage_LeaderboardUser*.json" 
- The "TotalDataFiles" record in the manifest file 

Are they same? 
If not, what cause that?
If yes, please share the file names.

**Comment by DeV1L** [comment] 2018-06-04 09:17
@blueww 
Here is the folder content:
![image](https://user-images.githubusercontent.com/8911626/40908372-34c43a0e-67ef-11e8-923c-e9a6f8b0f5c5.png)

And arenaxstorage_Leaderboard.manifest

`{"Version":2,"PayloadFormat":"Json","Checksum":15564613245429458971,"AccountName":"arenaxstorage","TableName":"Leaderboard","Timestamp":"2018-05-28T03:06:11.6482709Z","SplitSize":200000,"TotalDataFiles":1}`

Let me explain my case.

I'm exporting a bunch of tables everyday to blobs with prefix. It's daily backup.
![image](https://user-images.githubusercontent.com/8911626/40908470-7c912694-67ef-11e8-8cc3-9303a7992923.png)

![image](https://user-images.githubusercontent.com/8911626/40908489-8912963c-67ef-11e8-8ad2-fa39311c227a.png)

When I tried to restore them back I found that most tables are restored but several are not. They are the same for all backups. I tried to download them into local folder and restore from here (like on screenshot) and had the errors like on my first message. 

Also I tried to export tables to CSV and import them **manually** and it's failed [too](https://github.com/Azure/azure-storage-net-data-movement/issues/129#issuecomment-393094939).

All I can see that the tables had a structure for a time but later several new columns was added. I believe this is the problem.
![image](https://user-images.githubusercontent.com/8911626/40909019-2cc372d2-67f1-11e8-92f1-b602566aa116.png)

**Comment by blueww** [comment] 2018-06-05 10:38
@DeV1L 

Thanks for the detail information!
I am looking at this issue, but might need more time.

And could you please help to confirm the manifest  file and the json file are from same export running, instead from 2 export running. Since you use customized manifest file, export several times to same folder with same manifest file name can cause the issue.


Besides that, could you try to add something (like time tag) to the manifest file name to make sure it's different for each export, and see if this issue still repro?

**Comment by DeV1L** [comment] 2018-06-05 10:59
> And could you please help to confirm the manifest file and the json file are from same export running, instead from 2 export running.

Yes, I can share how I do it.

```
function Table-Backup
{
Param(
    [string] $StorageAccountNameSrc,
    [string] $StorageAccountKeySrc,
    [string] $StorageAccountNameDst,    
    [string] $StorageAccountKeyDst,
    $ContainerNameDst,
    $TargetFolder
)
foreach ($_ in $TablesSrc)
    {
    [string]$Manifest = $StorageAccountNameSrc + "_" + $_ + ".manifest"
    [string]$Uri = (Get-AzureStorageTable –Context $ContextSrc -Name $_).Uri

    Write-Output "Storage account for backup name: $StorageAccountNameSrc" -Verbose
    Write-Output "Source table: $Uri" -Verbose
    Write-Output "Destanation container: https://$StorageAccountNameDst.blob.core.windows.net/$ContainerNameDst/$TargetFolder" -Verbose
    Write-Output "Performing backup $_ from $StorageAccountNameSrc to $StorageAccountNameDst" -Verbose

    Set-Location $AzCopyDir
    & .\AzCopy.exe /Source:"$Uri" /Dest:https://$StorageAccountNameDst.blob.core.windows.net/$ContainerNameDst/$TargetFolder `
    /SourceKey:$StorageAccountKeySrc /Destkey:$StorageAccountKeyDst /Manifest:$Manifest `
    /Y /V:"$BackupLogsDir\tables\$Timestamp\$StorageAccountNameSrc"_"$ContainerSrc"_"$(Get-Date -format "yyyy-MM-dd_hhmm")" /Z:"$BackupLogsDir\tables\$Timestamp\$StorageAccountNameSrc"_"$(Get-Random)"
    }
}
```

**Comment by blueww** [comment] 2018-06-05 11:01
@DeV1L 

I can't repro the issue with the information from you on my machine. 
See my above message. Could you please give more details for your repro?

**Comment by DeV1L** [comment] 2018-06-07 12:44
@blueww 
According your comment 

> The data file (pattern "arenaxstorage_LeaderboardUser*.json") 's checksum in the title don't match the total checksum in the manifest file.

Does it mean that if I do the command 
`AzCopy /Source:https://arenaxtablesbackup.blob.core.windows.net/arenaxstorage/2018-06-06 /Dest:https://arenaxstoragedev.table.core.windows.net/Leaderboard /SourceKey:****** /Destkey:****** /Manifest:arenaxstorage_Leaderboard.manifest /EntityOperation:InsertOrReplace /Z /V`

And in the blobs I have:

- https://arenaxtablesbackup.blob.core.windows.net/arenaxstorage/2018-06-06/arenaxstorage_Leaderboard_0_0_2043D95E51E86C9B.json
- https://arenaxtablesbackup.blob.core.windows.net/arenaxstorage/2018-06-06/arenaxstorage_LeaderboardAllTime_0_0_9D50110B88A7A94D.json
- https://arenaxtablesbackup.blob.core.windows.net/arenaxstorage/2018-06-06/arenaxstorage_LeaderboardUser_0_0_BC10EA1A8F56299D.json

They all matches the pattern "arenaxstorage_Leaderboard*.json" and AzCopy will have error?

**Comment by blueww** [comment] 2018-06-08 02:07
Yes, I think this is the problem. Since we use "arenaxstorage_LeaderboardUser*.json" to match the data file, when you have other files with same pattern, then the checksum validation will fail.

Could you use the customized manifest file names which one is not prefix of others?

In the mean I will open a bug for AzCopy, and see if we can fix it.

**Comment by DeV1L** [comment] 2018-06-08 08:51
Will it work if I add a prefix for example "-backup"? It will be like this.
```
"arenaxstorage_Leaderboard-backup*.json"
"arenaxstorage_LeaderboardUser-backup*.json"
"arenaxstorage_LeaderboardAllTime-backup*.json"
```
By the way, what does it mean?

> table is in maintenance mode

**Comment by blueww** [comment] 2018-07-02 05:56
Close the issue as : The root cause of the issue is found, and find the resolution.
@DeV1L, I will close the issue now, please contact us if you need further assistance.

**Closed by blueww** 2018-07-02 05:56 UTC
Labels: help wanted
