### ISSUE TITLE
Blob download gets stuck

### ISSUE THREAD

**Issue by esrpgith** [Azure/azure-storage-net-data-movement#81] opened 2017-07-03 20:15 UTC
In our prod environment, Sometimes I see a behavior that a file is download about 60% and then nothing happens. It does not errors out nor returns. With this happening the download is stuck indefinitely. The handle to the file where it is written  is not released. I am assuming that the task that is create in StartSchedule() method in TransferScheduler class is running indefinitely. The dumps does not reveal anything. Is there a way to figure what might be the issue ?

Update:
I am using version 0.5.0

**Comment by bverhallen** [comment] 2017-07-05 11:01
I'm experiencing the same; seemingly random freezes on downloads in library version 0.5.0.145. Used function is TransferManager.DownloadAsync() function. The blob size doesn't seem to be of influence; it occurs with 150GB blobs and 10MB blobs in the same way.

**Comment by esrpgith** [comment] 2017-07-07 23:54
Does anybody have any ideas what could be happening.

**Comment by esrpgith** [comment] 2017-07-09 07:01
@bverhallen , were you able to mitigate your issue with version 0.5.3 ?

**Comment by bwang2019** [comment] 2017-08-02 17:48
I have seen the same issue. @bverhallen can you confirm that the issue has been fixed in v0.5.3?

**Comment by blueww** [comment] 2017-08-16 08:09
The download hang can happen on 0.5.0 since a Client library issue.
The issue has been fixed recently, and upgrade to latest DMlib will have the fix.

**Closed** 2017-08-31 08:08 UTC

**Comment by KiranBabu-Kirando** [comment] 2017-09-07 22:28
@blueww , can you describe why the download hang happened ? I would like to understand the root cause of the issue and how it was addressed.

**Comment by blueww** [comment] 2017-09-08 02:15
@KiranBabu-Kirando  
The fix is in XSCL 8.1.3 : https://github.com/Azure/azure-storage-net/releases/tag/v8.1.3

> •Blobs (Desktop) : Fixed a bug where the MaximumExecutionTime was not honored, leading to infinite wait, if due to a failure, e.g., a network failure after receiving the response headers, server stopped sending partial response.

**Comment by KiranBabu-Kirando** [comment] 2017-09-08 16:09
@blueww , Thanks for your explanation.

**Comment by jerickmsft** [comment] 2018-03-19 17:10
@blueww Do you know why the cancellation token is not being honored?  We are hitting this while using HttpClient.

**Comment by blueww** [comment] 2018-03-20 02:54
@jerickmsft 

PowerShell depends on DMlib(https://github.com/Azure/azure-storage-net-data-movement), and for DMlib  when get cancellation token, it will send cancel request to XSCL, and XSCL will cancel the request, after XSCL finish the cancel and return, DMlib/PowerShell can exist. So if XSCL hang, it won't have a chance to handle the cancel request from DMlib, then DMlib/PowerShell hang.

BTW, so you experience the hang again, which version of Powershell are you using?
