### ISSUE TITLE
Data Movement Library does not retry on Timeout exceptions

### ISSUE THREAD

**Issue by rduser** [Azure/azure-storage-net-data-movement#128] opened 2018-05-25 17:01 UTC
How can I configure the Data Movement library to retry on timeout exceptions?

Type: Microsoft.WindowsAzure.Storage.DataMovement.TransferException
Message: The transfer failed: The client could not finish the operation within specified timeout.
The client could not finish the operation within specified timeout..
ToString: Microsoft.WindowsAzure.Storage.DataMovement.TransferException: The transfer failed: The client could not finish the operation within specified timeout.
The client could not finish the operation within specified timeout.. ---> Microsoft.WindowsAzure.Storage.StorageException: The client could not finish the operation within specified timeout. ---> System.TimeoutException: The client could not finish the operation within specified timeout.
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 50
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass7.<CreateCallbackVoid>b__5(IAsyncResult ar) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 121
   at Microsoft.WindowsAzure.Storage.DataMovement.TransferControllers.BlockBasedBlobReader.<DownloadChunkAsync>d__16.MoveNext() in C:\Local\Jenkins\jobs\DM_UpgradeXSCL\workspace\lib\TransferControllers\TransferReaders\BlockBasedBlobReader.cs:line 306
   at Microsoft.WindowsAzure.Storage.DataMovement.TransferControllers.BlockBasedBlobReader.<DownloadBlockBlobAsync>d__15.MoveNext() in C:\Local\Jenkins\jobs\DM_UpgradeXSCL\workspace\lib\TransferControllers\TransferReaders\BlockBasedBlobReader.cs:line 274
   at Microsoft.WindowsAzure.Storage.DataMovement.TransferControllers.BlockBasedBlobReader.<DoWorkInternalAsync>d__12.MoveNext() in C:\Local\Jenkins\jobs\DM_UpgradeXSCL\workspace\lib\TransferControllers\TransferReaders\BlockBasedBlobReader.cs:line 98
   at Microsoft.WindowsAzure.Storage.DataMovement.TransferControllers.SyncTransferController.<DoWorkInternalAsync>d__13.MoveNext() in C:\Local\Jenkins\jobs\DM_UpgradeXSCL\workspace\lib\TransferControllers\SyncTransferController.cs:line 121
   at Microsoft.WindowsAzure.Storage.DataMovement.TransferControllers.TransferControllerBase.<DoWorkAsync>d__33.MoveNext() in C:\Local\Jenkins\jobs\DM_UpgradeXSCL\workspace\lib\TransferControllers\TransferControllerBase.cs:line 178
   at Microsoft.WindowsAzure.Storage.DataMovement.TransferScheduler.<ExecuteJobInternalAsync>d__22.MoveNext() in C:\Local\Jenkins\jobs\DM_UpgradeXSCL\workspace\lib\TransferScheduler.cs:line 208
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.DataMovement.TransferScheduler.<ExecuteJobInternalAsync>d__22.MoveNext() in C:\Local\Jenkins\jobs\DM_UpgradeXSCL\workspace\lib\TransferScheduler.cs:line 221
   at Microsoft.WindowsAzure.Storage.DataMovement.SingleObjectTransfer.<ExecuteAsync>d__8.MoveNext() in C:\Local\Jenkins\jobs\DM_UpgradeXSCL\workspace\lib\TransferJobs\SingleObjectTransfer.cs:line 226
   at Microsoft.WindowsAzure.Storage.DataMovement.TransferManager.<DoTransfer>d__73.MoveNext() in C:\Local\Jenkins\jobs\DM_UpgradeXSCL\workspace\lib\TransferManager.cs:line 1263

**Comment by blueww** [comment] 2018-05-28 05:30
@rduser 

DMLib will retry on request error, see retry policy in https://github.com/Azure/azure-storage-net-data-movement/blob/a32bdbc6567df054759c402ed0e4b47690cbbce6/lib/Transfer_RequestOptions.cs#L162

Currently DMlib don't open the retry policy in DMlib interface. But we have a workitem to open the customized retry policy. Do you want o vote for it.

And for you error, you might can try to decrease the TransferManager.Configurations.ParallelOperations, and see it can resolve the error. And DMlib can resume from this kind of error, you can just add the job again with same paramters to resume. We have a resume sample in: https://github.com/Azure/azure-storage-net-data-movement/blob/a32bdbc6567df054759c402ed0e4b47690cbbce6/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L311

**Comment by KiranBabu-Kirando** [comment] 2018-06-18 20:40
@blueww ,
I am also frequently getting these exceptions "The transfer failed: The client could not finish the operation within specified timeout".  You recommended to decrease TransferManager.Configurations.ParallelOperations this value. What is the value you recommend ?

On my wrapper class, I am setting these values on static constructor. Do they look good ?
            int threadsToUse = 300;
            ThreadPool.SetMinThreads(threadsToUse, threadsToUse / 2);
            
            ServicePointManager.DefaultConnectionLimit = 1000;
            ServicePointManager.Expect100Continue = false;
            TransferManager.Configurations.ParallelOperations = threadsToUse;

**Comment by blueww** [comment] 2018-06-19 01:48
@KiranBabu-Kirando 
I am not sure what's your machine configure. The default ParallelOperations  is cpu core count * 8.

I see currently you use 300, which looks might be too much. You might can start choose 10-20, then see if the error repro, if it repro, use less; else can try more.

**Comment by KiranBabu-Kirando** [comment] 2018-06-27 23:02
I have machines with 32 cores that's the reason I had 300. 
I tried ParallelOperations  with 256 (Cores*8), 64 and 32 and 2. for all these I am still getting timeout exceptions.

**Comment by blueww** [comment] 2018-06-28 03:10
@KiranBabu-Kirando 

It's a little wired that you meet the timeout even with very low ParallelOperations. It might be casued by the network between you machine and the Storage account are not good.

Could you share more about the user scenario of you:
1. the transfer direction (upload/download/copy)
2. the data size, and how frequently will you meet the error?
3. Is the DMlib running machine far from the Destination storage Account (and Source storage Account if any). Is it run on a VM in same region with the dest/source account? 

DMlib already will try 10 times on the transfer failure.
If still fail, you might can try to resume the transfer with same command and same transfer Context. This can resume the transfer and only transfer the left part.
Assume an interrupt occurs while copying your file, and 90% of the file has been transferred to Azure already. Then upon resume, we will only transfer the remaining 10% of the file.


If resume in the same process, you can just re-add the transfer job with same parameter and same Transfer Context. See a sample of resume in https://github.com/Azure/azure-storage-net-data-movement/blob/f0da1e1d1a6c872050c3dd420dc8aabe6ca6dfe2/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L172. 
This sample is for single file transfer, but directory file transfer is also the same. 
There's also some other sample in same file for: how to save the resume checkpoint in transfer context, and recreate the transfer context and resume.

**Comment by KiranBabu-Kirando** [comment] 2018-06-28 04:12
It is blob download. I am downloading from vm that is on-premesis. Blob is in West US. I tried to implement checkpoint for download but during testing  I see that the download is starting all over again from offset 0. Not sure what I am missing.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by blueww** [comment] 2018-06-28 09:30
@KiranBabu-Kirando 

Is your VM also on west us? 
Why do you think the download start from beginning? How long does the transfer has run and how much files downloaded before it fail? 

Could you share the code for how you use DMlib and how you resume the job? (hide credential like key/sas)

**Comment by KiranBabu-Kirando** [comment] 2018-06-29 17:23
@blueww  
Is there a way to debug why I am getting operationtimeout exceptions ?

**Comment by blueww** [comment] 2018-07-02 06:45
@KiranBabu-Kirando 

operationtimeout generally means after several retry of a request, DMlib doesn't receive the responds of the last retry in time. It can be caused by many things, like network issue, server is too busy. The error is reported from XSCL, and DMlib just wrapper it to TransferException and throw it.  
It might be difficult to find the root cause by debugging from the code level, But for your enviroment, since you have a big machine, but machine is far from the azure server (the machine is not VM in same region with azure server), so I suspect it might caused by the slow network. 
If you can provider the test account name, and the DMlib running time (UTC), we can help you to check the server status in the time, to see if the issue is related with server issue. The running time should be in 3 days, or the server log might already been rollover.

**Comment by blueww** [comment] 2018-07-17 02:18
@KiranBabu-Kirando 
As we don't hear any more commets from you for 2 weeks,  I will close the issue now.
Please contact us if you need further assistance.

**Closed by blueww** 2018-07-17 02:18 UTC

**Comment by kishore-jannarapu** [comment] 2021-06-21 07:11
in my case whitelisted the URL, *.vsassets.io resolved the issue.
