### ISSUE TITLE
TransferManager.DownloadAsync() SslStream object disposed

### ISSUE THREAD

**Issue by jamesr67** [Azure/azure-storage-net-data-movement#197] opened 2019-11-21 19:12 UTC
### Which service(blob, file) does this issue concern? 

Dowloading Blobs
Using TransferManager.DownloadAsync()
 
### Which version of the SDK was used?
SDK pulled in through nuget in Visual Studio.

Microsoft.Azure.Storage.DataMovement 1.1.0
which pulls in
Microsoft.Azure.KeyVault.Core 3.0.4
Microsoft.Azure.Storage.Blob 11.1.1
Microsoft.Azure.Storage.Common 11.1.1
Microsoft.Azure.Storage.File 11.1.1
Microsoft.Rest.ClientRuntime 2.3.20
Microsoft.Rest.ClientRuntime.Azure 3.3.19
Microsoft.WindowsAzure.ConfigurationManager 3.2.3

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)

Windows 10 build 17134

application targets .NETFramework 4.6.1
(4.7.2 installed)

### How can the problem be reproduced? It'd be better if the code caused the problem can be shared.

Problem is sporadic, but seen by multiple users (including those without a dev machine)
Briefly: our application initiates a number of jobs on azure batch (in parallel) and when a job has finished TransferManager is used to download the result files from a blob container (also in parallel)
some pseudo-code:

`

      Parallel.ForEach(
          AllJobInfo,
          (jobInfo) =>    
      {            
            SubmitJobOnAzure(jobInfo);
            var result = PollForCompletionAndGetResultInfo(jobInfo);
            var downloadTasks = new List<Task>();
           
            foreach (var blobName in result.blobs)
            {
                var container = new Container(new Uri(result.sasUrl));
                var blobRef = container.GetBlobReference(blobName);  // hidden blob type gnarliness for easy reading!
               downloadTasks.Add(
                      TransferManager.DownloadAsync(blobRef, targetPath, null, null, cancelationToken));
            }
            Task.WhenAll( downloadTasks ).Wait();
         });
`
 
### What problem was encountered?

Sporadically we encounter an exception  'cannot access disposed object: SslStream'

This has only occurred since we recently introduced the Azure download using the DataMovement/TransferManager and nowhere in the code do we use SslStream ourselves
 
### Have you found a mitigation/solution?

No.

**Comment by blueww** [comment] 2019-11-22 02:18
@jamesr67 
I can't get enough information for investigation just form the exception message.
Would you please give the full exception include stack trace?
And better with a dump file.

**Comment by jamesr67** [comment] 2019-11-25 12:14
@blueww 

{"Cannot access a disposed object.\r\nObject name: 'SslStream'."}


   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.EndRead(IAsyncResult asyncResult)
   at Microsoft.Azure.Storage.Core.ByteCountingStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)

**Comment by jamesr67** [comment] 2019-11-25 15:02
@blueww 

By enabling symbols servers in Visual Studio I was able to get line numbers on the stack:


```
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult) in f:\dd\NDP\fx\src\net\System\Net\_ConnectStream.cs:line 2002
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.EndRead(IAsyncResult asyncResult) in f:\dd\NDP\fx\src\net\System\Net\Http\HttpClientHandler.cs:line 1331
   at Microsoft.Azure.Storage.Core.ByteCountingStream.EndRead(IAsyncResult asyncResult) in C:\Program Files (x86)\Jenkins\workspace\dotnet-nuget\Lib\ClassLibraryCommon\Core\ByteCountingStream.cs:line 149
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization) in f:\dd\ndp\clr\src\BCL\system\threading\Tasks\FutureFactory.cs:line 1461
```

**Comment by jamesr67** [comment] 2019-11-25 18:49
I should add that the exception is arriving as a UnobservedTaskException, which suggests to me that the task(s) created by DownloadAsync() is are being marked as complete and the .Wait() is completed before the underlying ssl stream is finished.

**Comment by blueww** [comment] 2019-11-26 08:19
@jamesr67 
Thanks for the information!

From the trace, we can see the error is reported from DMlib's dependency. 
Since the error is not generated directly from DMlib code, we might can't find the root cause in a short time.

Besides that, We found a similar fixed issue in netcore: https://github.com/dotnet/corefx/issues/34033
So the issue might be related with .NET framework. 
As you are using .NET framework 4.6.1, do you mind change to 4.7.2 and see if the issue still repro?

**Comment by jamesr67** [comment] 2019-11-26 14:44
@blueww 

4.7.2 didn't make any difference (my machine already had 4.7.2 installed, but I changed the target version to that anyway)

I have created a small C# .NET console project that reproduces the problem.

[SslDisposalTest.zip](https://github.com/Azure/azure-storage-net-data-movement/files/3892228/SslDisposalTest.zip)

 In order to make it more reliably reproducible I am using cancellation tokens and forced garbage collection. Though I must emphasize that this is not required for the problem to occur; we have test users who are experiencing this without any cancellation happening.

In order to use this you will need an valid SAS to an Azure Storage container, with one or more large blobs (large enough to ensure that the download is ongoing when cancellation occurs).
I think that the error occurs more frequently when you download more files, but I also have it happen when downloading a single file.

After the downloads are started they will be cancelled by a timeout specified in the command line (in seconds) and a garbage collection is forced (this _seemed_ to make the exception more likely but I have no real evidence that this is actually the case).
I used 10 seconds to allow the download get going properly before the cancellation happens

The files are written to a fixed "downloads" directory (automatically created); remember to delete this afterwards as the download will pre-allocate disk space (which might be large)

Usage:

`SslDisposalTest.Exe <cancelation delay in seconds> <SAS> <blobName1> ... <blobNameN>`

typical output:
```
SslDisposalTest.exe 10 "https://<your SAS here>" blobName1 blobName2 blobName3
Starting wait;
Cancelled
Press <Enter> to finish.
Cannot access a disposed object.
Object name: 'SslStream'.
Cannot access a disposed object.
Object name: 'SslStream'.
```

I hope this helps.

**Comment by blueww** [comment] 2019-11-27 09:47
@jamesr67 
Thanks for the repro program!
I will need some times to investigate, and will update you when get some result.

**Comment by jamesr67** [comment] 2019-11-27 16:23
@blueww 
Thanks for looking at this.

For a laugh; I re-targeted the repro program at .NET Core 3.0, and I get a similar error but wrapped up in another exception and with a slightly different stack trace.
So it's not unique to .NET Framework

Exception message:
`The read operation failed, see inner exception.`

Inner Exception:
```
Cannot access a disposed object.
Object name: 'SslStream'.
```

```
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslStream.<ReadAsyncInternal>d__214`1.MoveNext()
```

I think I've done all I can here.

**Comment by blueww** [comment] 2019-11-28 07:16
@jamesr67 
Thanks for the sharing!

1. I can repro this same issue only with Storage Client library (aka. XSCL, DMlib depends on it.), without DMlib. So this issue is inside XSCL. 
I will share the repro program with you soon.
Would you like to open an issue for XSCL team? (I will also try to contact them for that.)

2. As you say the issue also repro wihtout cancel. If so, when it repro without cancel, will other error happen? We suspect other error might make the DMlib thread stop, then cause the exception.

3. When you find the issue, do you get the exception always from  UnobservedTaskException(like the repro program), or from Wait of DMlib job.

**Comment by blueww** [comment] 2020-05-21 14:37
@jamesr67
As not get your responds for a long time, I will close this issue.
Feel free to contact us again if you need further assistance.

**Closed by blueww** 2020-05-21 14:37 UTC
